# CREAR UNA CLASE AIRE ACONDICINADO
# EL CONSTRUCTOR DEBE FIJAR LA TEMPERATURA INICIAL EN 24 GRADOS
# CREA UN METODO BAJAR_TEMPERATURA(SELF, GRADOS)
# REGLA DE NEGOCIO: NO PERMITAS QUE LA TEMPERATURA BAJE DE 16 GRADOS. SI EL USUARIO INTENTA BAJAR A MENOS, IMPRIME UN ERROR.
# INSTANCIA EL OBJETO Y USA EL METODO PARA INTENTAR BAJARLO A 10 GRADOS
class AireAcondicionado:
    grados = input("ingrese el grado: ")
    def __init__(self, temperatura =24 ):
    
        def bajar_temperatura(self, grados):
            self.grados == self.temperatura or self.grados <= 16
            print("Error")

            

        

